### ISSUE TITLE
Rackspace - Cannot deploy salt in a VM if the 'ssh_keyfile' setting is not set and there is no password set for the vm.

### ISSUE THREAD

**Issue by complistic-gaff** [saltstack-formulas/salt-cloud-reactor#6]
After setting up this reactor I'm hitting an issue where it seems it cant bootstrap newly created Rackspace servers (created in there web GUI) because it does not have ssh access with a password or ssh key.

I'm getting the following error message back after creating a new server.

```
SaltCloudSystemExit: Cannot deploy salt in a VM if the 'ssh_keyfile' setting is not set and there is no password set for the vm. Check your provider for the 'change_password' option.
```

Full output from salt-master debug output:

```
[DEBUG   ] OpenStack authenticating using apikey
[DEBUG   ] ['test6']
[DEBUG   ] ['test6']
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-07-03T17:11:07.076921'}
[DEBUG   ] Gathering reactors for tag salt/event/new_client
[DEBUG   ] Sending event - data = {<SNIP>}
[DEBUG   ] Gathering reactors for tag salt/cloud/test6/cache_node_diff
[DEBUG   ] Loaded node data for test6:
{'_uuid': None,
 'extra': {'access_ip': '119.9.25.139',
           'availability_zone': None,
           'created': '2015-07-03T17:10:04Z',
           'disk_config': 'MANUAL',
           'flavorId': 'general1-1',
           'hostId': '96bf27ef41903c52c63d63add2837e937522afc9bb453a3596e66403',
           'imageId': '93346217-ef91-4983-803e-2027891d1cdb',
           'key_name': '<MYPUBKEY>',
           'metadata': {},
           'password': None,
           'tenantId': '<SNIP>',
           'updated': '2015-07-03T17:11:16Z',
           'uri': 'https://syd.servers.api.rackspacecloud.com/v2/<SNIP>/servers/<SNIP>'},
 'id': '<SNIP>',
 'image': None,
 'name': 'test6',
 'private_ips': ['<SNIP>'],
 'public_ips': ['<SNIP>'],
 'size': None,
 'state': 0}
[DEBUG   ] VM is now running
[DEBUG   ] Using IP address <SNIP>
[DEBUG   ] Salt interface set to: <SNIP>
[DEBUG   ] LazyLoaded nested.output
Exception occurred in runner cloud.create: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/cloud.py", line 160, in create
    info = client.create(provider, instances, **create_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 389, in create
    mapper.create(vm_))
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/openstack.py", line 854, in create
    ret = salt.utils.cloud.bootstrap(vm_, __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 308, in bootstrap
    'Cannot deploy salt in a VM if the \'ssh_keyfile\' setting '
SaltCloudSystemExit: Cannot deploy salt in a VM if the 'ssh_keyfile' setting is not set and there is no password set for the vm. Check your provider for the 'change_password' option.
```

From what I can tell Rackspace only provide the password on server creation, so you wouldn’t be able to use password auth with servers created from there Web GUI.

I have also tried installing a pub key on the new server and adding `ssh_keyfile` to both my `cloud.profile` and `cloud.provider` configs like so:

```
  ssh_keyfile: '/path/to/private_key'
```

But this did not make any diffrence and the error message was the same.

My Environment:

```
# salt-master --version
salt-master 2015.5.2 (Lithium)
# python --version
Python 2.7.9
# uname -a
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

Creating servers using the `salt-cloud` command line tool works fine and bootstraps correctly.

**Comment by complistic-gaff** [comment]
Okay I have worked this out by looking at the config described here: https://github.com/saltstack/salt/issues/20932

I needed to set `ssh_key_file` and not `ssh_keyfile` like stated in the error.

After that all seems to be working on rackspace with `salt-master 2015.5.2 (Lithium)` :)
